apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fullname" . }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.host.name }}
      http:
        paths:
          - path: {{.Values.routePath }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "fullname" .}}
                port:
                  number: {{ .Values.port }}
