apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  replicas: {{.Values.Replicate}}
  selector:
    matchLabels:
      {{- include "selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.bar.repository}}:{{ .Values.image.bar.tag}}"
          imagePullPolicy: {{ .Values.image.bar.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
              protocol: TCP
          env:
            - name: "MESSAGE"
              value: {{ .Values.message }}
            - name: "PORT"
              value: "{{ .Values.port }}"
            - name: "ROUTE_PATH"
              value: {{ .Values.routePath }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" .}}
  labels:
    {{- include "labels" . | nindent 4 }}
  namespace: {{ .Values.Namespace }}
spec:
  ports:
    - name: http
      port: {{ .Values.port }}
      protocol: TCP
      targetPort: {{ .Values.port }}
  selector:
    {{- include "selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP

